sudo: required

language: node_js

node_js:
  - stable

before_install:
  - wget https://github.com/sharkdp/hyperfine/releases/download/v1.5.0/hyperfine_1.5.0_amd64.deb

install:
  - npm install

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

# yarn pnp integration test disabled for node 13 because of https://github.com/yarnpkg/yarn/issues/7642
script:
  - npm run depcruise
  - npm run test:glob
  - npm run test:cover
  - npm run lint
  - npm run test:yarn-pnp

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

branches:
  except:
    - gh-pages

cache:
  directories:
    - node_modules
